### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by ronilbhatia** [jamestouri/toGather#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments
* Add welcome message
* Add placeholder link to live site
* each wiki page should be bulleted
---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
* MVPs seem to deviate from the MVP list. For example, your first MVP is to 'Build Groups and Events', while the MVP list for this project has this as your two separate MVPs. I would say to stick as closely to those MVPs as possible - anything additional you want to add on can be a Bonus feature.
* You have 8 MVPs listed in total - should only have 7, with the remaining being bonus. Choose 4 key features, rather than 5, and have additional features be bonus.
* From your current MVP list, it's unclear what your CRUD feature is. If it's groups or events, state as such in the MVP and explicitly call out the ability to create, edit, and delete these items.
* Have a minimum 3 bullet points for each of the MVP Features that you are building out (this excludes Heroku and Production README). For most of these you should be able to add the following
  * Adequate Styling
  * Smooth, bug-free navigation
  * Adequate and appropriate seeds to demonstrate the feature
---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
* Below tables, you need to add in lines for the foreign keys and what tables they are referencing, as well as which columns you are indexing on, and whether you are enforcing uniqueness - see bluebird example (bullet points beneath each table)
* Do groups have an owner? If so, will likely need a foreign key column of `user_id` or `owner_id`. If this is being handled differently, we can discuss.
* `datetime` might be a better data structure than just `time` for events since they will likely have a specified time as well
---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
* Looks good! Just change snake_case to camelCase on keys.
* Are your events, users, or groups going to have associated images? If so you will need to include an `imageUrl` for these in your front-end state. You won't need a column in your back-end table for this as it will be achieved through special ActiveStorage associations - we can discuss more when we meet.
---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
* Missing HTML & API sections - HTML section is just to render the `static_pages#root` view
* Event routes need work 
  * Event resource should be plural (i.e. namespace under `events` not `event`)
  * None of the CRUD routes for events need to be nested - we can pass up the `group_id` through a hidden input on the event form when we make it. The only route that would need to be nested would be an events index to show all the events for a specific group - this would be `/groups/:group_id/events` - no other route requires nesting. We can discuss more when we meet.
* Routes for `comments`, `join_groups` and `rsvps` are superfluous and do not require nesting.
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
* missing ':' on some wildcards
* `Root`, `App`, `NavBar`, and `Footer` should be backticked.
* is `/comments/new` really going to be a frontend route? Usually comment forms are a component of a different route - for example in your events show page `/events/:eventId` you would likely have a `CommentForm` at the bottom of this page so that users can add comments for that event. We can then pass the `eventId` up through a hidden input to receive on the back-end (this is why our back-end route to create a comment does not need to be nested).

**Comment by jamestouri** [comment]
Hi Ronil, 
Please look at the edits I've made. 
Thanks

**Comment by ronilbhatia** [comment]
Good job!
